<?php
require_once '../../includes/auth.php';
require_once '../../includes/config.php';
require_once '../../includes/functions.php';

if (!hasPermission('supervisor')) {
    header("Location: /autoservice/dashboard.php");
    exit();
}

// Get all job cards
$jobCards = $pdo->query("SELECT j.*, u.full_name as created_by_name 
                        FROM job_cards j 
                        JOIN users u ON j.created_by = u.id 
                        ORDER BY j.created_at DESC")->fetchAll();

// Get all invoices
$invoices = $pdo->query("SELECT i.*, j.customer_name, j.vehicle_model, u.full_name as generated_by_name
                        FROM invoices i
                        JOIN job_cards j ON i.job_card_id = j.id
                        JOIN users u ON i.generated_by = u.id
                        ORDER BY i.created_at DESC")->fetchAll();
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Finance Dashboard</title>
    <link rel="stylesheet" href="../../css/style.css">
</head>
<body>
    <?php include '../../includes/header.php'; ?>
    
    <div class="container">
        <h1>Finance Dashboard</h1>
        <p>Welcome, <?php echo $_SESSION['full_name']; ?> (Supervisor)</p>
        
        <div class="tabs">
            <button class="tab-btn active" onclick="openTab('jobCards')">Job Cards</button>
            <button class="tab-btn" onclick="openTab('invoices')">Invoices</button>
            <button class="tab-btn" onclick="openTab('reports')">Reports</button>
        </div>
        
        <!-- Job Cards Tab -->
        <div id="jobCards" class="tab-content" style="display: block;">
            <h2>All Job Cards</h2>
            <table>
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Customer</th>
                        <th>Vehicle</th>
                        <th>License</th>
                        <th>Status</th>
                        <th>Created By</th>
                        <th>Created</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($jobCards as $job): ?>
                    <tr>
                        <td><?php echo $job['id']; ?></td>
                        <td><?php echo htmlspecialchars($job['customer_name']); ?></td>
                        <td><?php echo htmlspecialchars($job['vehicle_model']); ?></td>
                        <td><?php echo htmlspecialchars($job['vehicle_license']); ?></td>
                        <td><span class="status-badge <?php echo str_replace('_', '-', $job['status']); ?>">
                            <?php echo ucwords(str_replace('_', ' ', $job['status'])); ?>
                        </span></td>
                        <td><?php echo htmlspecialchars($job['created_by_name']); ?></td>
                        <td><?php echo formatDate($job['created_at']); ?></td>
                        <td>
                            <a href="../service/view.php?id=<?php echo $job['id']; ?>" class="btn small">View</a>
                            <?php if ($job['status'] === 'completed'): ?>
                                <button onclick="generateInvoice(<?php echo $job['id']; ?>)" class="btn small">Generate Invoice</button>
                            <?php endif; ?>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
        
        <!-- Invoices Tab -->
        <div id="invoices" class="tab-content">
            <h2>Generated Invoices</h2>
            <table>
                <thead>
                    <tr>
                        <th>Invoice #</th>
                        <th>Job Card</th>
                        <th>Customer</th>
                        <th>Vehicle</th>
                        <th>Amount</th>
                        <th>Generated By</th>
                        <th>Date</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($invoices as $invoice): ?>
                    <tr>
                        <td>INV-<?php echo $invoice['id']; ?></td>
                        <td>JC-<?php echo $invoice['job_card_id']; ?></td>
                        <td><?php echo htmlspecialchars($invoice['customer_name']); ?></td>
                        <td><?php echo htmlspecialchars($invoice['vehicle_model']); ?></td>
                        <td>$<?php echo number_format($invoice['amount'], 2); ?></td>
                        <td><?php echo htmlspecialchars($invoice['generated_by_name']); ?></td>
                        <td><?php echo formatDate($invoice['created_at'] ?? ''); ?></td>
                        <td>
                            <a href="view_invoice.php?id=<?php echo $invoice['id']; ?>" class="btn small">View</a>
                            <a href="print_invoice.php?id=<?php echo $invoice['id']; ?>" target="_blank" class="btn small">Print</a>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
        
        <!-- Reports Tab -->
        <div id="reports" class="tab-content">
            <h2>Financial Reports</h2>
            <div class="report-options">
                <div class="report-card" onclick="generateReport('daily')">
                    <h3>Daily Report</h3>
                    <p>Generate today's financial summary</p>
                </div>
                <div class="report-card" onclick="generateReport('weekly')">
                    <h3>Weekly Report</h3>
                    <p>Generate this week's financial summary</p>
                </div>
                <div class="report-card" onclick="generateReport('monthly')">
                    <h3>Monthly Report</h3>
                    <p>Generate this month's financial summary</p>
                </div>
                <div class="report-card" onclick="openCustomReportModal()">
                    <h3>Custom Report</h3>
                    <p>Generate report for custom date range</p>
                </div>
            </div>
            
            <div id="reportResults" style="margin-top: 20px; display: none;">
                <h3>Report Results</h3>
                <div id="reportData"></div>
                <button onclick="printReport()" class="btn">Print Report</button>
                <button onclick="exportToExcel()" class="btn">Export to Excel</button>
            </div>
        </div>
    </div>
    
    <!-- Custom Report Modal -->
    <div id="customReportModal" class="modal">
        <div class="modal-content">
            <span class="close" onclick="closeModal('customReportModal')">&times;</span>
            <h2>Generate Custom Report</h2>
            <form id="customReportForm">
                <div class="form-group">
                    <label for="start_date">Start Date</label>
                    <input type="date" id="start_date" name="start_date" required>
                </div>
                <div class="form-group">
                    <label for="end_date">End Date</label>
                    <input type="date" id="end_date" name="end_date" required>
                </div>
                <div class="form-group">
                    <label for="report_type">Report Type</label>
                    <select id="report_type" name="report_type" required>
                        <option value="summary">Summary Report</option>
                        <option value="detailed">Detailed Report</option>
                        <option value="invoice">Invoice Report</option>
                    </select>
                </div>
                <button type="submit" class="btn">Generate Report</button>
            </form>
        </div>
    </div>
    
    <?php include '../../includes/footer.php'; ?>
    <script src="../../js/script.js"></script>
    <script>
    // Tab functionality
    function openTab(tabName) {
        const tabContents = document.getElementsByClassName('tab-content');
        for (let i = 0; i < tabContents.length; i++) {
            tabContents[i].style.display = 'none';
        }
        
        const tabButtons = document.getElementsByClassName('tab-btn');
        for (let i = 0; i < tabButtons.length; i++) {
            tabButtons[i].classList.remove('active');
        }
        
        document.getElementById(tabName).style.display = 'block';
        event.currentTarget.classList.add('active');
    }
    
    // Invoice generation
    function generateInvoice(jobId) {
        if (confirm('Generate invoice for this job card?')) {
            fetch('generate_invoice.php', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify({ jobId })
            })
            .then(response => response.json())
            .then(data => {
                if (data.success) {
                    alert('Invoice generated successfully');
                    location.reload();
                } else {
                    alert('Error: ' + data.message);
                }
            })
            .catch(error => {
                console.error('Error:', error);
                alert('An error occurred');
            });
        }
    }
    
    // Report generation
    function generateReport(type) {
        fetch('generate_report.php', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({ type })
        })
        .then(response => response.json())
        .then(data => {
            if (data.success) {
                document.getElementById('reportData').innerHTML = data.html;
                document.getElementById('reportResults').style.display = 'block';
            } else {
                alert('Error: ' + data.message);
            }
        })
        .catch(error => {
            console.error('Error:', error);
            alert('An error occurred');
        });
    }
    
    function openCustomReportModal() {
        openModal('customReportModal');
    }
    
    document.getElementById('customReportForm').addEventListener('submit', function(e) {
        e.preventDefault();
        
        const formData = {
            start_date: document.getElementById('start_date').value,
            end_date: document.getElementById('end_date').value,
            report_type: document.getElementById('report_type').value
        };
        
        fetch('generate_custom_report.php', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify(formData)
        })
        .then(response => response.json())
        .then(data => {
            if (data.success) {
                document.getElementById('reportData').innerHTML = data.html;
                document.getElementById('reportResults').style.display = 'block';
                closeModal('customReportModal');
            } else {
                alert('Error: ' + data.message);
            }
        })
        .catch(error => {
            console.error('Error:', error);
            alert('An error occurred');
        });
    });
    
    function printReport() {
        const printWindow = window.open('', '_blank');
        printWindow.document.write(`
            <html>
                <head>
                    <title>Financial Report</title>
                    <style>
                        body { font-family: Arial, sans-serif; }
                        table { width: 100%; border-collapse: collapse; }
                        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
                        th { background-color: #f2f2f2; }
                        .report-title { text-align: center; margin-bottom: 20px; }
                        .report-date { text-align: right; margin-bottom: 20px; }
                    </style>
                </head>
                <body>
                    <div class="report-title"><h1>Financial Report</h1></div>
                    <div class="report-date">Generated on: ${new Date().toLocaleString()}</div>
                    ${document.getElementById('reportData').innerHTML}
                </body>
            </html>
        `);
        printWindow.document.close();
        printWindow.print();
    }
    
    function exportToExcel() {
        // This would typically use a library like SheetJS in a real implementation
        alert('Excel export functionality would be implemented here');
    }
    </script>
</body>
</html>